[package]
name = "datapath"
version = "0.1.0"
edition = "2021"
authors = ["Thne"]
description = "A minimal jq-like path extractor and updater for structured data in Rust"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Thneonl/datapath"
keywords = ["json", "yaml", "path", "query", "jq"]
categories = ["command-line-utilities", "parsing"]

[[bin]]
name = "datapath"
path = "src/cli.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
winnow = "0.5"

[features]
default = []
update = []
