# XQPath 调试配置模板
# 专为调试和开发设计的配置

debug:
  level: trace
  output: stderr
  file: "~/.xqpath/logs/debug.log"
  timing: true

performance:
  memory_limit: "2GB"
  timeout: "300s"
  cache_size: 100
  parallel_jobs: 1

paths:
  cache_dir: "~/.xqpath/debug/cache"
  log_dir: "~/.xqpath/debug/logs"
  config_dir: "~/.xqpath"

features:
  colored_output: true
  interactive_mode: true
  auto_backup: true
